### ISSUE TITLE
[Feature Request] Progress Bar for uploading

### ISSUE THREAD

**Issue by Masy** [navopw/PolluxClient#2]
It's kinda annoying when uploading bigger files/screens and you don't know when they are done

**Comment by navopw** [comment]
I already thought about that. Will probably add it in v1.3

**Comment by navopw** [comment]
Will be added in Pollux v2 (aka Pollux 2.0)

**Comment by navopw** [comment]
I tried to add it but the Outputstream only shows 0 and 100, because the whole byte[] is written in one time. idk.
